# ============================================================================
# Azure Pipelines Linux Build Template
# ============================================================================
# 
# Perform cleanup tasks for Linux agents, such as clearing caches or temporary files.
#
# ============================================================================

# ============================================================================
# PARAMETERS
# ============================================================================
parameters:
  - name: displayName
    type: string

  - name: BuildOperatingSystem
    type: string

  - name: CleanupDirectory
    type: string
    
# ============================================================================
# JOBS
# ============================================================================
jobs:
  - job: Cleanup
    displayName: ${{ parameters.displayName }}

    pool:
      name: Default
      demands:
        - Agent.OS -equals Linux
        #- Agent.OSArchitecture -equals ${{ arch }}
        # add additional demands here

    steps:
      # ====================================================================
      # CHECKOUT & CLEANUP
      # ====================================================================
      - checkout: self
        name: step1

      - bash: |
          echo "Cleaning CPM cache directory...${{ parameters.CleanupDirectory }}"
          rm -rdf "${{ parameters.CleanupDirectory }}"
          echo "Cleanup successful"
        displayName: Cleanup CPM Cache

